### ISSUE TITLE
Unable to run individual `runtime-integration-tests`

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#13776]
```
> runtime-integration-tests/testOnly *RuntimeVisualizationsTest
...
[info]   List(Response(Some(55ffc96f-c134-4942-81d0-6e351ab475f2), PushContextResponse(b3d1b575-ee39-4833-b29e-e58e7e91c8b9)), Response(None, ExecutionFailed(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Failure("NoClassDefFoundError", None)))) did not contain the same elements as List(Response(Some(55ffc96f-c134-4942-81d0-6e351ab475f2), PushContextResponse(b3d1b575-ee39-4833-b29e-e58e7e91c8b9)), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00aa-bc6d-182d9ded4a26, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), None, Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00ab-0528-671485844679, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Enso_Test.Test.Main", "Standard.Base.Data.Numbers.Number", "foo"), Vector())), Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00ac-7073-b1345e964b7d, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Standard.Base.Data.Numbers", 
...
```
while
```
> runtime-integration-tests/test
```
passes. Regressed in https://github.com/enso-org/enso/commit/277f33f1bd49418b02b0ea8cc76020b0b0a49a5e

**Comment by JaroslavTulach** [comment]
- I was running:
```
runtime-integration-tests/testOnly *Runtime*Test
```
- this morning. When working on #13768
- the tests passed

**Comment by JaroslavTulach** [comment]
Trying again:
```
enso$ rm -rf *; git checkout -f .
Updated 9161 paths from the index
enso$ git log | head -n5
commit 343fdd86ff867723581e43a38fc7f7ae7b865e97
Author: Keziah Wesley <kaz@lambdaverse.org>
Date:   Wed Aug 13 07:30:36 2025 -0700

    Clean up visualization, data server logic (#13754)
enso$ sbt
sbt:enso> buildEngineDistribution
sbt:enso> runtime-integration-tests/testOnly *RuntimeVisualizationsTest
```
and the result is... **yes, it fails**:
```
[info] RuntimeVisualizationsTest:
[enso::EnsoContext] WARNING: Initializing the context in a different working directory than the one containing the project root. This may lead to relative paths not behaving as advertised by `File.new`. Please run the engine inside of `/tmp` directory.ntegration-tests / Test / testOnly 3s
[info] - should emit visualization update when expression is computed *** FAILED *** (1 minute, 9 seconds)
[info]   List(Response(Some(b3875f40-dc1d-4a37-ad21-899e36040f91), PushContextResponse(c61076d0-8c46-435d-8a04-b6504b3aed66)), Response(None, ExecutionFailed(c61076d0-8c46-435d-8a04-b6504b3aed66, Failure("NoClassDefFoundError", None)))) did not contain the same elements as List(Response(Some(b3875f40-dc1d-4a37-ad21-899e36040f91), PushContextResponse(c61076d0-8c46-435d-8a04-b6504b3aed66)), Response(None, ExpressionUpdates(c61076d0-8c46-435d-8a04-b6504b3aed66, Set(ExpressionUpdate(00000000-0000-00aa-a2e5-bf62cc264f72, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), None, Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(c61076d0-8c46-435d-8a04-b6504b3aed66, Set(ExpressionUpdate(00000000-0000-00ab-851b-049c015f4b15, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Enso_Test.Test.Main", "Standard.Base.Data.Numbers.Number", "foo"), Vector())), Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(c61076d0-8c46-435d-8a04-b6504b3aed66, Set(ExpressionUpdate(00000000-0000-00ac-47b3-701a5d3a40e1, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Standard.Base.Data.Numbers", "Standard.Base.Data.Numbers.Integer", "+"), Vector())), Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(c61076d0-8c46-435d-8a04-b6504b3aed66, Set(ExpressionUpdate(6bb0da94-1548-4b18-804f-d8d68ca53c49, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), None, Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExecutionComplete(c61076d0-8c46-435d-8a04-b6504b3aed66))) (RuntimeVisualizationsTest.scala:332)
[info] - should emit visualization update when expression is cached *** FAILED *** (1 minute, 3 seconds)
```

**Comment by hubertp** [comment]
Unfortunately `runtime-integration-tests/testOnly *Runtime*Test` appears to exercise different initialization paths than `runtime-integration-tests/testOnly *RuntimeVisualizationsTest` or so it seems?

Behind the scenes `NoClassDef` error was due to initialization error for `DataflowError`.
