### PR TITLE
Removes `ModuleScopeBuilder` from `Module`

### LINKED ISSUE #13776: Unable to run individual `runtime-integration-tests`
```
> runtime-integration-tests/testOnly *RuntimeVisualizationsTest
...
[info]   List(Response(Some(55ffc96f-c134-4942-81d0-6e351ab475f2), PushContextResponse(b3d1b575-ee39-4833-b29e-e58e7e91c8b9)), Response(None, ExecutionFailed(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Failure("NoClassDefFoundError", None)))) did not contain the same elements as List(Response(Some(55ffc96f-c134-4942-81d0-6e351ab475f2), PushContextResponse(b3d1b575-ee39-4833-b29e-e58e7e91c8b9)), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00aa-bc6d-182d9ded4a26, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), None, Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00ab-0528-671485844679, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Enso_Test.Test.Main", "Standard.Base.Data.Numbers.Number", "foo"), Vector())), Vector(ExecutionTime(0)), false, true, Value(None, None))))), Response(None, ExpressionUpdates(b3d1b575-ee39-4833-b29e-e58e7e91c8b9, Set(ExpressionUpdate(00000000-0000-00ac-7073-b1345e964b7d, Some(ExpressionType(Vector("Standard.Base.Data.Numbers.Integer"), Vector())), Some(MethodCall(MethodPointer("Standard.Base.Data.Numbers", 
...
```
while
```
> runtime-integration-tests/test
```
passes. Regressed in https://github.com/enso-org/enso/commit/277f33f1bd49418b02b0ea8cc76020b0b0a49a5e

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

- continuation of #13716
- and #13709
- this time we remove `ModuleScopeBuilder` from `Module`
- the idea is that `Module` has a mutable piece `ModuleScope` reference
- that reference is updated iff `ModuleScopeBuilder.finish()` is called
- 5b36d3b fixes #13776

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests continue to pass

### CODE REVIEW

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java [hunk 1]
```diff
@@ -55,12 +55,15 @@
 import org.enso.text.buffer.Rope;
 import org.slf4j.LoggerFactory;
 
-/** Represents a source module with a known location. */
+/**
+ * Represents a source module with a known location. The state of {@link Module} may change as the
+ * user manipulates it source in the Enso Studio. The immutable state is captured inside of {@link
```
Comment (Akirathan) [inline engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java:60]: nit: I have never heard the term "Enso Studio" before, better to use "Enso IDE".

**Review by Akirathan — APPROVED** [review]

File: engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java (hunk 1 above)
Comment (JaroslavTulach) [reply engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java:60]: - It is a [historical name used by Ara](https://github.com/enso-org/enso/blob/9f2132eb8acdec297c89c1b4a197842b9dd327a5/docs/runtime/runtime-features.md?plain=1#L62) in one of her documents.
- I recently found it when working on #13593
- I definitely like it more than _Enso GUI_
- I probably like it more than _Enso IDE_
- it feels so _"data analytics"_!

**Review by hubertp — COMMENTED** [review]
May I suggest to first fix https://github.com/enso-org/enso/issues/13776 before going deeper down the rabbit hole?

**Comment by JaroslavTulach** [comment]
> May I suggest to first fix #13776 before going deeper down the rabbit hole?

- I was running:
```
runtime-integration-tests/testOnly *Runtime*Test
```
- this morning. The tests passed. But testing just `RuntimeVisualizationsTest` is was failing. With 5b36d3b one can also execute:
```
runtime-integration-tests/testOnly *RuntimeVisualizationsTest
```
and the tests succeed.
